#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 5.3.2 (swiftlang-1200.0.45 clang-1200.0.32.28)
#ifndef ZENPLUGINSDK_SWIFT_H
#define ZENPLUGINSDK_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <Foundation/Foundation.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(ns_consumed)
# define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
#else
# define SWIFT_RELEASES_ARGUMENT
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if !defined(IBSegueAction)
# define IBSegueAction
#endif
#if __has_feature(modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreGraphics;
@import CoreLocation;
@import Foundation;
@import ObjectiveC;
@import UIKit;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="ZENPluginSDK",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif



SWIFT_PROTOCOL_NAMED("HostAppProtocol")
@protocol HostAppProtocol
@optional
- (NSString * _Nullable)menuButtonImage SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nullable)backButtonImage SWIFT_WARN_UNUSED_RESULT;
- (void)trackScreenView:(NSString * _Nonnull)name;
- (void)trackScreenView:(NSString * _Nonnull)name trackingId:(NSString * _Nonnull)trackingId;
- (void)trackEvent:(NSString * _Nonnull)category action:(NSString * _Nonnull)action optionalValues:(NSDictionary<NSString *, id> * _Nullable)optionalValues;
- (void)trackEvent:(NSString * _Nonnull)category action:(NSString * _Nonnull)action optionalValues:(NSDictionary<NSString *, id> * _Nullable)optionalValues trackingId:(NSString * _Nonnull)trackingId;
- (void)getUserData:(void (^ _Nonnull)(NSError * _Nullable, id _Nullable))completion;
@end

@class UIViewController;

@interface UIApplication (SWIFT_EXTENSION(ZENPluginSDK))
+ (UIViewController * _Nullable)topViewControllerWithController:(UIViewController * _Nullable)controller SWIFT_WARN_UNUSED_RESULT;
@end



@class UIColor;

@interface UIImage (SWIFT_EXTENSION(ZENPluginSDK))
- (nullable instancetype)initWithColor:(UIColor * _Nonnull)color size:(CGSize)size;
@end


@interface UIViewController (SWIFT_EXTENSION(ZENPluginSDK))
- (BOOL)isModal SWIFT_WARN_UNUSED_RESULT;
@end

typedef SWIFT_ENUM(NSInteger, ZENOrder, open) {
  ZENOrderAsis = 0,
  ZENOrderName = 1,
  ZENOrderPriority = 2,
};

@class ZENPluginInfo;
@class NSBundle;
@class NSCoder;

SWIFT_CLASS("_TtC12ZENPluginSDK22ZENPluginAUXController")
@interface ZENPluginAUXController : UIViewController
@property (nonatomic, readonly, strong) ZENPluginInfo * _Nonnull info;
@property (nonatomic, copy) void (^ _Nullable okHandler)(ZENPluginInfo * _Nonnull);
@property (nonatomic, copy) void (^ _Nullable cancelHandler)(void);
@property (nonatomic, copy) NSDictionary<NSString *, id> * _Nullable agreementParams;
@property (nonatomic, copy) NSDictionary<NSString *, id> * _Nullable downloadParams;
@property (nonatomic, copy) NSDictionary<NSString *, id> * _Nullable updateParams;
@property (nonatomic, copy) NSDictionary<NSString *, id> * _Nullable assetsParams;
@property (nonatomic, copy) NSString * _Nullable cannotLoadPlugin;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil SWIFT_UNAVAILABLE;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
- (nonnull instancetype)initWithInfo:(ZENPluginInfo * _Nonnull)info OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)viewDidLoad;
- (void)viewDidLayoutSubviews;
@end


SWIFT_CLASS_NAMED("ZENPluginConstants")
@interface ZENPluginConstants : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull pluginId;)
+ (NSString * _Nonnull)pluginId SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull assetsURL;)
+ (NSString * _Nonnull)assetsURL SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull menuImage;)
+ (NSString * _Nonnull)menuImage SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull backImage;)
+ (NSString * _Nonnull)backImage SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC12ZENPluginSDK18ZENPluginSDKObject")
@interface ZENPluginSDKObject : NSObject
- (nonnull instancetype)init:(NSDictionary<NSString *, id> * _Nonnull)dictionary;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (NSDictionary<NSString *, id> * _Nonnull)jsonObject SWIFT_WARN_UNUSED_RESULT;
- (NSData * _Nullable)jsonData SWIFT_WARN_UNUSED_RESULT;
+ (NSArray * _Nonnull)arrayOf:(NSArray * _Nonnull)array SWIFT_WARN_UNUSED_RESULT;
@end

enum ZENPluginType : NSInteger;
@class ZENSDKDependencies;
@class ZENSDKAssets;
@class ZENSDKSettings;
@class ZENSDKIcons;
enum ZENPluginStatus : NSInteger;

SWIFT_CLASS("_TtC12ZENPluginSDK13ZENPluginInfo")
@interface ZENPluginInfo : ZENPluginSDKObject
@property (nonatomic, readonly, copy) NSString * _Nonnull id;
@property (nonatomic, readonly) enum ZENPluginType type;
@property (nonatomic, readonly) NSInteger priority;
@property (nonatomic, readonly, copy) NSString * _Nullable name;
@property (nonatomic, readonly, copy) NSString * _Nullable version;
@property (nonatomic, readonly, copy) NSString * _Nullable language;
@property (nonatomic, readonly) BOOL enabled;
@property (nonatomic, readonly) BOOL forceUpdate;
@property (nonatomic, readonly, copy) NSString * _Nonnull autoUpdate;
@property (nonatomic, readonly) NSInteger licenseRevision;
@property (nonatomic, readonly) BOOL dataConsent;
@property (nonatomic, readonly, copy) NSString * _Nonnull menuPath;
@property (nonatomic, readonly, strong) ZENSDKDependencies * _Nullable dependencies;
@property (nonatomic, readonly, strong) ZENSDKAssets * _Nullable assets;
@property (nonatomic, readonly, strong) ZENSDKSettings * _Nullable settings;
@property (nonatomic, readonly, strong) ZENSDKAssets * _Nullable reactNative;
@property (nonatomic, readonly, strong) ZENSDKAssets * _Nullable native;
@property (nonatomic, readonly, strong) ZENSDKIcons * _Nullable icons;
@property (nonatomic, readonly) BOOL widget;
@property (nonatomic, readonly, copy) NSString * _Nullable brief;
@property (nonatomic, readonly, strong) ZENPluginInfo * _Nullable freshVersion;
- (nonnull instancetype)init:(NSDictionary<NSString *, id> * _Nonnull)dictionary;
- (NSDictionary<NSString *, id> * _Nonnull)jsonObject SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nullable)moduleName SWIFT_WARN_UNUSED_RESULT;
- (BOOL)devMode SWIFT_WARN_UNUSED_RESULT;
- (BOOL)downloaded SWIFT_WARN_UNUSED_RESULT;
- (BOOL)agreementAccepted SWIFT_WARN_UNUSED_RESULT;
- (BOOL)isWidgetAvailable SWIFT_WARN_UNUSED_RESULT;
- (BOOL)newVersionAvailable SWIFT_WARN_UNUSED_RESULT;
- (BOOL)isEnabled SWIFT_WARN_UNUSED_RESULT;
- (BOOL)assetsAvailable SWIFT_WARN_UNUSED_RESULT;
- (BOOL)assetsDownloaded SWIFT_WARN_UNUSED_RESULT;
- (void)loadImage:(NSString * _Nonnull)value completion:(void (^ _Nonnull)(UIImage * _Nonnull))completion;
- (void)saveValue:(NSString * _Nonnull)key value:(id _Nonnull)value;
- (id _Nullable)loadValue:(NSString * _Nonnull)key SWIFT_WARN_UNUSED_RESULT;
- (void)saveData:(NSDictionary<NSString *, id> * _Nonnull)data;
- (NSDictionary<NSString *, id> * _Nonnull)loadData SWIFT_WARN_UNUSED_RESULT;
- (UIImage * _Nullable)localImage:(NSString * _Nonnull)value SWIFT_WARN_UNUSED_RESULT;
- (enum ZENPluginStatus)canShowUI SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end



SWIFT_PROTOCOL_NAMED("ZENPluginProtocol")
@protocol ZENPluginProtocol
- (UIViewController * _Nullable)pluginController SWIFT_WARN_UNUSED_RESULT;
- (void)initializePlugin:(NSDictionary<NSString *, id> * _Nonnull)params;
- (void)stopBackgroundProcesses;
- (void)resumeBackgroundProcesses;
- (void)addObserver;
- (void)removeObserver;
@optional
- (void)didReceivePushNotification:(NSDictionary<NSString *, id> * _Nonnull)aps;
@end

@class ZENPluginSDKStyle;
@class ZENWidget;
@class ZENWidgetLine;
@class UIFont;

SWIFT_CLASS("_TtC12ZENPluginSDK12ZENPluginSDK")
@interface ZENPluginSDK : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, strong) ZENPluginSDK * _Nonnull instance;)
+ (ZENPluginSDK * _Nonnull)instance SWIFT_WARN_UNUSED_RESULT;
+ (void)setInstance:(ZENPluginSDK * _Nonnull)value;
@property (nonatomic, readonly, strong) ZENPluginSDKStyle * _Nonnull style;
@property (nonatomic, weak) id <HostAppProtocol> _Nullable hostAppDelegate;
/// //// handlers ////////
@property (nonatomic, copy) void (^ _Nullable pluginsListUpdated)(NSArray<ZENPluginInfo *> * _Nonnull);
@property (nonatomic, copy) void (^ _Nullable pluginsLoadingFailed)(void);
@property (nonatomic, copy) void (^ _Nullable pluginDownloaded)(ZENPluginInfo * _Nonnull);
@property (nonatomic, copy) void (^ _Nullable pluginDownloadingFailed)(ZENPluginInfo * _Nonnull);
@property (nonatomic, copy) void (^ _Nullable assetsDownloaded)(ZENPluginInfo * _Nonnull);
@property (nonatomic, copy) void (^ _Nullable assetsDownloadingFailed)(ZENPluginInfo * _Nonnull);
@property (nonatomic, copy) void (^ _Nullable widgetInfoUpdated)(ZENWidget * _Nonnull);
@property (nonatomic, copy) void (^ _Nullable widgetLineUpdated)(ZENWidgetLine * _Nonnull);
@property (nonatomic, copy) void (^ _Nullable pluginWantsToShowUI)(ZENPluginInfo * _Nonnull);
@property (nonatomic, copy) void (^ _Nullable pluginWantsToShowMenu)(void);
@property (nonatomic, copy) void (^ _Nullable pluginWantsToDismiss)(void);
@property (nonatomic, copy) void (^ _Nullable pluginLoadingComplete)(ZENPluginInfo * _Nonnull);
/// //////////////////////
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (void)initializeSDK:(NSDictionary<NSString *, id> * _Nonnull)params;
- (void)updatePluginsFromNetwork;
- (NSArray<ZENPluginInfo *> * _Nonnull)pluginsOrderedBy:(enum ZENOrder)order section:(NSString * _Nullable)section SWIFT_WARN_UNUSED_RESULT;
- (NSArray<ZENPluginInfo *> * _Nonnull)widgetsOrderedBy:(enum ZENOrder)order section:(NSString * _Nullable)section SWIFT_WARN_UNUSED_RESULT;
- (ZENPluginAUXController * _Nullable)loadAUXController:(ZENPluginInfo * _Nonnull)info messages:(NSDictionary<NSString *, id> * _Nullable)messages SWIFT_WARN_UNUSED_RESULT;
- (UIViewController * _Nullable)loadUI:(ZENPluginInfo * _Nonnull)info SWIFT_WARN_UNUSED_RESULT;
- (ZENWidget * _Nullable)loadWidget:(ZENPluginInfo * _Nonnull)info SWIFT_WARN_UNUSED_RESULT;
- (ZENPluginInfo * _Nullable)pluginByIdentity:(NSString * _Nonnull)identity SWIFT_WARN_UNUSED_RESULT;
- (void)addObserver:(ZENPluginInfo * _Nonnull)info;
- (void)removeObserver:(ZENPluginInfo * _Nonnull)info;
- (void)revokeDataProcessing:(ZENPluginInfo * _Nonnull)info completion:(void (^ _Nonnull)(NSDictionary<NSString *, id> * _Nullable, NSError * _Nullable))completion;
- (BOOL)isPluginLoaded:(ZENPluginInfo * _Nonnull)info SWIFT_WARN_UNUSED_RESULT;
- (void)closePlugin:(ZENPluginInfo * _Nonnull)info;
- (void)closeAllPlugins;
- (void)removeAssets:(ZENPluginInfo * _Nonnull)info;
- (void)removePlugin:(ZENPluginInfo * _Nonnull)info;
- (void)switchSandBoxMode:(ZENPluginInfo * _Nonnull)info devURL:(NSString * _Nullable)devURL;
- (void)setCustomStyle:(NSDictionary<NSString *, id> * _Nonnull)params;
- (void)setDefaultFont:(UIFont * _Nonnull)font;
- (void)setBaseURL:(NSString * _Nonnull)url;
- (void)setHeader:(NSString * _Nonnull)key value:(NSString * _Nonnull)value;
- (void)didReceivePushWithNotification:(NSDictionary<NSString *, id> * _Nonnull)notification;
/// call it from didFinishLaunchingWithOptions (for example) or implement your own code
- (void)registerForLocalNotifications:(UIApplication * _Nonnull)application;
/// call it from applicationDidBecomeActive or implement your own code
- (void)removeLocalNotifications:(UIApplication * _Nonnull)application;
@end


@interface ZENPluginSDK (SWIFT_EXTENSION(ZENPluginSDK))
- (void)getUserData:(void (^ _Nonnull)(NSError * _Nullable, id _Nullable))completion;
@end


@interface ZENPluginSDK (SWIFT_EXTENSION(ZENPluginSDK)) <CLLocationManagerDelegate>
- (void)isLocationServiceAvailable:(void (^ _Nonnull)(BOOL))callback;
@end



@interface ZENPluginSDK (SWIFT_EXTENSION(ZENPluginSDK))
- (void)createNotification:(NSInteger)identity text:(NSString * _Nonnull)text datetime:(NSDate * _Nonnull)datetime sound:(NSString * _Nonnull)sound;
- (void)updateNotification:(NSInteger)identity text:(NSString * _Nonnull)text datetime:(NSDate * _Nonnull)datetime sound:(NSString * _Nonnull)sound;
- (void)deleteNotification:(NSInteger)identity;
@end



@interface ZENPluginSDK (SWIFT_EXTENSION(ZENPluginSDK))
- (void)APIGETRequest:(id <ZENPluginProtocol> _Nonnull)sender url:(NSURL * _Nonnull)url completion:(void (^ _Nonnull)(NSError * _Nullable, id _Nullable))completion;
- (void)APIPOSTRequest:(id <ZENPluginProtocol> _Nonnull)sender url:(NSURL * _Nonnull)url params:(NSDictionary<NSString *, id> * _Nullable)params completion:(void (^ _Nonnull)(NSError * _Nullable, id _Nullable))completion;
- (void)APIRequest:(id <ZENPluginProtocol> _Nonnull)sender url:(NSURL * _Nonnull)url method:(NSString * _Nonnull)method params:(NSDictionary<NSString *, id> * _Nullable)params completion:(void (^ _Nonnull)(NSError * _Nullable, id _Nullable))completion;
- (void)APIRequest:(id <ZENPluginProtocol> _Nonnull)sender url:(NSURL * _Nonnull)url method:(NSString * _Nonnull)method params:(NSDictionary<NSString *, id> * _Nullable)params headers:(NSDictionary<NSString *, NSString *> * _Nullable)headers completion:(void (^ _Nonnull)(NSError * _Nullable, id _Nullable))completion;
@end


@interface ZENPluginSDK (SWIFT_EXTENSION(ZENPluginSDK))
- (void)trackScreenView:(NSString * _Nonnull)name;
- (void)trackScreenView:(NSString * _Nonnull)name trackingId:(NSString * _Nonnull)trackingId;
- (void)trackEvent:(NSString * _Nonnull)category action:(NSString * _Nonnull)action;
- (void)trackEvent:(NSString * _Nonnull)category action:(NSString * _Nonnull)action optionalValues:(NSDictionary<NSString *, id> * _Nullable)optionalValues;
- (void)trackEvent:(NSString * _Nonnull)category action:(NSString * _Nonnull)action optionalValues:(NSDictionary<NSString *, id> * _Nullable)optionalValues trackingId:(NSString * _Nonnull)trackingId;
@end



@class UIBarButtonItem;

@interface ZENPluginSDK (SWIFT_EXTENSION(ZENPluginSDK))
- (NSString * _Nullable)pluginId:(id <ZENPluginProtocol> _Nonnull)sender SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nullable)assetsURL:(id <ZENPluginProtocol> _Nonnull)sender SWIFT_WARN_UNUSED_RESULT;
- (ZENPluginInfo * _Nullable)pluginMetadata:(id <ZENPluginProtocol> _Nonnull)sender SWIFT_WARN_UNUSED_RESULT;
- (void)sendWidgetData:(id <ZENPluginProtocol> _Nonnull)sender widget:(ZENWidget * _Nonnull)widget;
- (void)requestToOpenController:(id <ZENPluginProtocol> _Nonnull)sender;
- (void)requestToShowMenu;
- (void)requestToClose;
- (NSString * _Nullable)menuButtonImage SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nullable)backButtonImage SWIFT_WARN_UNUSED_RESULT;
- (UIBarButtonItem * _Nullable)menuButton SWIFT_WARN_UNUSED_RESULT;
- (void)saveValue:(id <ZENPluginProtocol> _Nonnull)sender key:(NSString * _Nonnull)key value:(id _Nonnull)value;
- (id _Nullable)loadValue:(id <ZENPluginProtocol> _Nonnull)sender key:(NSString * _Nonnull)key SWIFT_WARN_UNUSED_RESULT;
- (void)saveData:(id <ZENPluginProtocol> _Nonnull)sender dic:(NSDictionary<NSString *, id> * _Nonnull)dic;
- (NSDictionary<NSString *, id> * _Nonnull)loadData:(id <ZENPluginProtocol> _Nonnull)sender SWIFT_WARN_UNUSED_RESULT;
- (void)sendEvent:(id <ZENPluginProtocol> _Nonnull)sender type:(NSString * _Nonnull)type payload:(NSDictionary<NSString *, id> * _Nonnull)payload;
- (void)revokeDataProcessingConsent:(id <ZENPluginProtocol> _Nonnull)sender completion:(void (^ _Nonnull)(NSDictionary<NSString *, id> * _Nullable, NSError * _Nullable))completion;
@end

@class UINavigationController;

@interface ZENPluginSDK (SWIFT_EXTENSION(ZENPluginSDK))
+ (void)runPlugin:(UIViewController * _Nonnull)sender info:(ZENPluginInfo * _Nonnull)info push:(BOOL)push ncClass:(SWIFT_METATYPE(UINavigationController) _Nonnull)ncClass;
@end


SWIFT_CLASS("_TtC12ZENPluginSDK16ZENPluginSDKInfo")
@interface ZENPluginSDKInfo : ZENPluginSDKObject
- (nonnull instancetype)init:(NSDictionary<NSString *, id> * _Nonnull)dictionary;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC12ZENPluginSDK18ZENPluginSDKMethod")
@interface ZENPluginSDKMethod : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


@class ZENPluginSDKStyleFont;
@class ZENPluginSDKStyleView;
@class ZENPluginSDKStyleTable;
@class ZENPluginSDKStyleButtons;

SWIFT_CLASS("_TtC12ZENPluginSDK17ZENPluginSDKStyle")
@interface ZENPluginSDKStyle : NSObject
@property (nonatomic, readonly, strong) ZENPluginSDKStyleFont * _Nonnull fonts;
@property (nonatomic, readonly, strong) ZENPluginSDKStyleView * _Nonnull view;
@property (nonatomic, readonly, strong) ZENPluginSDKStyleTable * _Nonnull table;
@property (nonatomic, readonly, strong) ZENPluginSDKStyleButtons * _Nonnull buttons;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtCC12ZENPluginSDK17ZENPluginSDKStyle23ZENPluginSDKStyleObject")
@interface ZENPluginSDKStyleObject : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtCC12ZENPluginSDK17ZENPluginSDKStyle21ZENPluginSDKStyleFont")
@interface ZENPluginSDKStyleFont : ZENPluginSDKStyleObject
@property (nonatomic, readonly, strong) UIFont * _Nonnull title;
@property (nonatomic, readonly, strong) UIFont * _Nonnull subtitle;
@property (nonatomic, readonly, strong) UIFont * _Nonnull body;
@property (nonatomic, readonly, strong) UIFont * _Nonnull defaultFont;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtCC12ZENPluginSDK17ZENPluginSDKStyle21ZENPluginSDKStyleView")
@interface ZENPluginSDKStyleView : ZENPluginSDKStyleObject
@property (nonatomic, readonly, strong) UIColor * _Nonnull backgroundColor;
@property (nonatomic, readonly, strong) UIColor * _Nonnull textColor;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtCC12ZENPluginSDK17ZENPluginSDKStyle22ZENPluginSDKStyleTable")
@interface ZENPluginSDKStyleTable : ZENPluginSDKStyleObject
@property (nonatomic, readonly, strong) UIColor * _Nonnull backgroundColor;
@property (nonatomic, readonly, strong) UIColor * _Nonnull cellBackgroundColor;
@property (nonatomic, readonly, strong) UIColor * _Nonnull separatorColor;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtCC12ZENPluginSDK17ZENPluginSDKStyle24ZENPluginSDKStyleButtons")
@interface ZENPluginSDKStyleButtons : ZENPluginSDKStyleObject
@property (nonatomic, readonly, strong) UIColor * _Nonnull backgroundColor;
@property (nonatomic, readonly, strong) UIColor * _Nonnull titleColor;
@property (nonatomic, readonly, strong) UIColor * _Nonnull tintColor;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


typedef SWIFT_ENUM_NAMED(NSInteger, ZENPluginStatus, "ZENPluginStatus", open) {
  ZENPluginStatusCanShowUI = 0,
  ZENPluginStatusNoLicense = 1,
  ZENPluginStatusNeedUpdate = 2,
  ZENPluginStatusNoBundle = 3,
  ZENPluginStatusNoAssets = 4,
};

typedef SWIFT_ENUM(NSInteger, ZENPluginType, open) {
  ZENPluginTypeNative = 0,
  ZENPluginTypeReact = 1,
};


SWIFT_CLASS("_TtC12ZENPluginSDK12ZENSDKAssets")
@interface ZENSDKAssets : ZENPluginSDKObject
@property (nonatomic, readonly, copy) NSString * _Nullable bundleUrl;
@property (nonatomic, readonly, copy) NSString * _Nullable checksum;
@property (nonatomic, readonly, copy) NSString * _Nullable binary;
@property (nonatomic, readonly, copy) NSString * _Nullable moduleName;
- (nonnull instancetype)init:(NSDictionary<NSString *, id> * _Nonnull)dictionary;
- (NSDictionary<NSString *, id> * _Nonnull)jsonObject SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC12ZENPluginSDK18ZENSDKConfirmation")
@interface ZENSDKConfirmation : ZENPluginSDKObject
- (nonnull instancetype)init:(NSDictionary<NSString *, id> * _Nonnull)dictionary;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

enum ZENSDKEnvironment : NSInteger;

SWIFT_CLASS("_TtC12ZENPluginSDK15ZENSDKConstants")
@interface ZENSDKConstants : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSTimeInterval tryDownloadAgainTimeout;)
+ (NSTimeInterval)tryDownloadAgainTimeout SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSTimeInterval sendEventInterval;)
+ (NSTimeInterval)sendEventInterval SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger sendEventAmount;)
+ (NSInteger)sendEventAmount SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger maxEventCount;)
+ (NSInteger)maxEventCount SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull platform;)
+ (NSString * _Nonnull)platform SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull app_id;)
+ (NSString * _Nonnull)app_id SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull errorDomain;)
+ (NSString * _Nonnull)errorDomain SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull client_key;)
+ (NSString * _Nonnull)client_key SWIFT_WARN_UNUSED_RESULT;
+ (enum ZENSDKEnvironment)environment:(NSString * _Nullable)env SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC12ZENPluginSDK18ZENSDKDependencies")
@interface ZENSDKDependencies : ZENPluginSDKObject
@property (nonatomic, readonly, copy) NSString * _Nullable sdkVersion;
@property (nonatomic, readonly, copy) NSString * _Nullable appVersion;
- (nonnull instancetype)init:(NSDictionary<NSString *, id> * _Nonnull)dictionary;
- (NSDictionary<NSString *, id> * _Nonnull)jsonObject SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

typedef SWIFT_ENUM(NSInteger, ZENSDKEnvironment, open) {
  ZENSDKEnvironmentDevelopment = 0,
  ZENSDKEnvironmentTesting = 1,
  ZENSDKEnvironmentProduction = 2,
};


SWIFT_CLASS("_TtC12ZENPluginSDK11ZENSDKIcons")
@interface ZENSDKIcons : ZENPluginSDKObject
@property (nonatomic, readonly, copy) NSString * _Nullable twoX;
@property (nonatomic, readonly, copy) NSString * _Nullable threeX;
- (nonnull instancetype)init:(NSDictionary<NSString *, id> * _Nonnull)dictionary;
- (NSDictionary<NSString *, id> * _Nonnull)jsonObject SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC12ZENPluginSDK14ZENSDKSettings")
@interface ZENSDKSettings : ZENPluginSDKObject
@property (nonatomic, readonly, copy) NSString * _Nullable layoutVariant;
@property (nonatomic, readonly, copy) NSString * _Nullable backendApi;
- (nonnull instancetype)init:(NSDictionary<NSString *, id> * _Nonnull)dictionary;
- (NSDictionary<NSString *, id> * _Nonnull)jsonObject SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC12ZENPluginSDK15ZENSDKapiParams")
@interface ZENSDKapiParams : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull appVersion;)
+ (NSString * _Nonnull)appVersion SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull sdkVersion;)
+ (NSString * _Nonnull)sdkVersion SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull country;)
+ (NSString * _Nonnull)country SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull language;)
+ (NSString * _Nonnull)language SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull device_id;)
+ (NSString * _Nonnull)device_id SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull platform;)
+ (NSString * _Nonnull)platform SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull sim_country;)
+ (NSString * _Nonnull)sim_country SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull dealer_country;)
+ (NSString * _Nonnull)dealer_country SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull plugin;)
+ (NSString * _Nonnull)plugin SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull plugins;)
+ (NSString * _Nonnull)plugins SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC12ZENPluginSDK15ZENSDKenvParams")
@interface ZENSDKenvParams : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull development;)
+ (NSString * _Nonnull)development SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull testing;)
+ (NSString * _Nonnull)testing SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull production;)
+ (NSString * _Nonnull)production SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC12ZENPluginSDK16ZENSDKinfoParams")
@interface ZENSDKinfoParams : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull device_id;)
+ (NSString * _Nonnull)device_id SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull app_version;)
+ (NSString * _Nonnull)app_version SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull sdk_version;)
+ (NSString * _Nonnull)sdk_version SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull environment;)
+ (NSString * _Nonnull)environment SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull language;)
+ (NSString * _Nonnull)language SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull sim_country;)
+ (NSString * _Nonnull)sim_country SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull dealer_country;)
+ (NSString * _Nonnull)dealer_country SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull dealer;)
+ (NSString * _Nonnull)dealer SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull clientKey;)
+ (NSString * _Nonnull)clientKey SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC12ZENPluginSDK19ZENSDKnotifications")
@interface ZENSDKnotifications : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSNotificationName _Nonnull pluginsListUpdated;)
+ (NSNotificationName _Nonnull)pluginsListUpdated SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSNotificationName _Nonnull pluginsLoadingFailed;)
+ (NSNotificationName _Nonnull)pluginsLoadingFailed SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSNotificationName _Nonnull pluginDownloaded;)
+ (NSNotificationName _Nonnull)pluginDownloaded SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSNotificationName _Nonnull pluginDownloadingFailed;)
+ (NSNotificationName _Nonnull)pluginDownloadingFailed SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSNotificationName _Nonnull assetsDownloaded;)
+ (NSNotificationName _Nonnull)assetsDownloaded SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSNotificationName _Nonnull assetsDownloadingFailed;)
+ (NSNotificationName _Nonnull)assetsDownloadingFailed SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSNotificationName _Nonnull widgetInfoUpdated;)
+ (NSNotificationName _Nonnull)widgetInfoUpdated SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSNotificationName _Nonnull widgetLineUpdated;)
+ (NSNotificationName _Nonnull)widgetLineUpdated SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSNotificationName _Nonnull pluginWantsToShowUI;)
+ (NSNotificationName _Nonnull)pluginWantsToShowUI SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSNotificationName _Nonnull pluginWantsToShowMenu;)
+ (NSNotificationName _Nonnull)pluginWantsToShowMenu SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSNotificationName _Nonnull pluginWantsToDismiss;)
+ (NSNotificationName _Nonnull)pluginWantsToDismiss SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSNotificationName _Nonnull pluginLoadingComplete;)
+ (NSNotificationName _Nonnull)pluginLoadingComplete SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class ZENPluginSDKStyleParamsFont;
@class ZENPluginSDKStyleParamsView;
@class ZENPluginSDKStyleParamsTable;
@class ZENPluginSDKStyleParamsButtons;

SWIFT_CLASS("_TtC12ZENPluginSDK17ZENSDKstyleParams")
@interface ZENSDKstyleParams : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) SWIFT_METATYPE(ZENPluginSDKStyleParamsFont) _Nonnull fonts;)
+ (SWIFT_METATYPE(ZENPluginSDKStyleParamsFont) _Nonnull)fonts SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) SWIFT_METATYPE(ZENPluginSDKStyleParamsView) _Nonnull view;)
+ (SWIFT_METATYPE(ZENPluginSDKStyleParamsView) _Nonnull)view SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) SWIFT_METATYPE(ZENPluginSDKStyleParamsTable) _Nonnull table;)
+ (SWIFT_METATYPE(ZENPluginSDKStyleParamsTable) _Nonnull)table SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) SWIFT_METATYPE(ZENPluginSDKStyleParamsButtons) _Nonnull buttons;)
+ (SWIFT_METATYPE(ZENPluginSDKStyleParamsButtons) _Nonnull)buttons SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtCC12ZENPluginSDK17ZENSDKstyleParams27ZENPluginSDKStyleParamsFont")
@interface ZENPluginSDKStyleParamsFont : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull title;)
+ (NSString * _Nonnull)title SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull subtitle;)
+ (NSString * _Nonnull)subtitle SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull body;)
+ (NSString * _Nonnull)body SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSArray<NSString *> * _Nonnull allKeys;)
+ (NSArray<NSString *> * _Nonnull)allKeys SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtCC12ZENPluginSDK17ZENSDKstyleParams27ZENPluginSDKStyleParamsView")
@interface ZENPluginSDKStyleParamsView : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull backgroundColor;)
+ (NSString * _Nonnull)backgroundColor SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull textColor;)
+ (NSString * _Nonnull)textColor SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSArray<NSString *> * _Nonnull allKeys;)
+ (NSArray<NSString *> * _Nonnull)allKeys SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtCC12ZENPluginSDK17ZENSDKstyleParams28ZENPluginSDKStyleParamsTable")
@interface ZENPluginSDKStyleParamsTable : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull backgroundColor;)
+ (NSString * _Nonnull)backgroundColor SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull cellBackgroundColor;)
+ (NSString * _Nonnull)cellBackgroundColor SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull separatorColor;)
+ (NSString * _Nonnull)separatorColor SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSArray<NSString *> * _Nonnull allKeys;)
+ (NSArray<NSString *> * _Nonnull)allKeys SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtCC12ZENPluginSDK17ZENSDKstyleParams30ZENPluginSDKStyleParamsButtons")
@interface ZENPluginSDKStyleParamsButtons : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull backgroundColor;)
+ (NSString * _Nonnull)backgroundColor SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull titleColor;)
+ (NSString * _Nonnull)titleColor SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull tintColor;)
+ (NSString * _Nonnull)tintColor SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSArray<NSString *> * _Nonnull allKeys;)
+ (NSArray<NSString *> * _Nonnull)allKeys SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC12ZENPluginSDK9ZENWidget")
@interface ZENWidget : ZENPluginSDKObject
@property (nonatomic, copy) NSString * _Nullable pluginId;
@property (nonatomic, strong) UIImage * _Nullable image;
@property (nonatomic, copy) NSURL * _Nullable imageURL;
@property (nonatomic, copy) NSString * _Nullable title;
@property (nonatomic, copy) NSArray<ZENWidgetLine *> * _Nullable lines;
- (nonnull instancetype)init:(NSDictionary<NSString *, id> * _Nonnull)dictionary;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC12ZENPluginSDK15ZENWidgetAction")
@interface ZENWidgetAction : NSObject
@property (nonatomic, weak) ZENWidgetLine * _Nullable line;
@property (nonatomic, copy) void (^ _Nullable handler)(void);
@property (nonatomic, copy) NSString * _Nullable title;
@property (nonatomic, strong) UIImage * _Nullable image;
@property (nonatomic, copy) NSString * _Nullable imageURL;
@property (nonatomic) BOOL isEnabled;
@property (nonatomic) BOOL isHidden;
- (nonnull instancetype)initWithTitle:(NSString * _Nullable)title image:(UIImage * _Nullable)image handler:(void (^ _Nullable)(void))handler;
- (nonnull instancetype)initWithTitle:(NSString * _Nullable)title imageURL:(NSString * _Nullable)imageURL handler:(void (^ _Nullable)(void))handler;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

enum ZENlineType : NSInteger;

SWIFT_CLASS("_TtC12ZENPluginSDK13ZENWidgetLine")
@interface ZENWidgetLine : ZENPluginSDKObject
@property (nonatomic, weak) ZENWidget * _Nullable widget;
@property (nonatomic) enum ZENlineType type;
@property (nonatomic) NSInteger lines;
@property (nonatomic, copy) NSString * _Nullable richText;
@property (nonatomic, copy) NSURL * _Nullable iconName;
@property (nonatomic, strong) UIImage * _Nullable icon;
@property (nonatomic) float progress;
@property (nonatomic) BOOL loading;
@property (nonatomic, copy) NSArray<ZENWidgetAction *> * _Nullable actions;
- (nonnull instancetype)init:(NSDictionary<NSString *, id> * _Nonnull)dictionary;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

typedef SWIFT_ENUM(NSInteger, ZENlineType, open) {
  ZENlineTypeNone = 0,
  ZENlineTypeText = 1,
  ZENlineTypeIconText = 2,
  ZENlineTypeIconProgress = 3,
  ZENlineTypeLoading = 4,
  ZENlineTypeButtons = 5,
};


SWIFT_CLASS("_TtC12ZENPluginSDK10confParams")
@interface confParams : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull titleText;)
+ (NSString * _Nonnull)titleText SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull bodyText;)
+ (NSString * _Nonnull)bodyText SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull okButtonText;)
+ (NSString * _Nonnull)okButtonText SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull cancelButtonText;)
+ (NSString * _Nonnull)cancelButtonText SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC12ZENPluginSDK14lineTypeParams")
@interface lineTypeParams : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC12ZENPluginSDK14messagesParams")
@interface messagesParams : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull agreementParams;)
+ (NSString * _Nonnull)agreementParams SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull downloadParams;)
+ (NSString * _Nonnull)downloadParams SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull updateParams;)
+ (NSString * _Nonnull)updateParams SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull assetsParams;)
+ (NSString * _Nonnull)assetsParams SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull cannotLoadPlugin;)
+ (NSString * _Nonnull)cannotLoadPlugin SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC12ZENPluginSDK12widgetParams")
@interface widgetParams : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop
#endif

#elif defined(__x86_64__) && __x86_64__
// Generated by Apple Swift version 5.3.2 (swiftlang-1200.0.45 clang-1200.0.32.28)
#ifndef ZENPLUGINSDK_SWIFT_H
#define ZENPLUGINSDK_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <Foundation/Foundation.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(ns_consumed)
# define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
#else
# define SWIFT_RELEASES_ARGUMENT
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if !defined(IBSegueAction)
# define IBSegueAction
#endif
#if __has_feature(modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreGraphics;
@import CoreLocation;
@import Foundation;
@import ObjectiveC;
@import UIKit;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="ZENPluginSDK",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif



SWIFT_PROTOCOL_NAMED("HostAppProtocol")
@protocol HostAppProtocol
@optional
- (NSString * _Nullable)menuButtonImage SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nullable)backButtonImage SWIFT_WARN_UNUSED_RESULT;
- (void)trackScreenView:(NSString * _Nonnull)name;
- (void)trackScreenView:(NSString * _Nonnull)name trackingId:(NSString * _Nonnull)trackingId;
- (void)trackEvent:(NSString * _Nonnull)category action:(NSString * _Nonnull)action optionalValues:(NSDictionary<NSString *, id> * _Nullable)optionalValues;
- (void)trackEvent:(NSString * _Nonnull)category action:(NSString * _Nonnull)action optionalValues:(NSDictionary<NSString *, id> * _Nullable)optionalValues trackingId:(NSString * _Nonnull)trackingId;
- (void)getUserData:(void (^ _Nonnull)(NSError * _Nullable, id _Nullable))completion;
@end

@class UIViewController;

@interface UIApplication (SWIFT_EXTENSION(ZENPluginSDK))
+ (UIViewController * _Nullable)topViewControllerWithController:(UIViewController * _Nullable)controller SWIFT_WARN_UNUSED_RESULT;
@end



@class UIColor;

@interface UIImage (SWIFT_EXTENSION(ZENPluginSDK))
- (nullable instancetype)initWithColor:(UIColor * _Nonnull)color size:(CGSize)size;
@end


@interface UIViewController (SWIFT_EXTENSION(ZENPluginSDK))
- (BOOL)isModal SWIFT_WARN_UNUSED_RESULT;
@end

typedef SWIFT_ENUM(NSInteger, ZENOrder, open) {
  ZENOrderAsis = 0,
  ZENOrderName = 1,
  ZENOrderPriority = 2,
};

@class ZENPluginInfo;
@class NSBundle;
@class NSCoder;

SWIFT_CLASS("_TtC12ZENPluginSDK22ZENPluginAUXController")
@interface ZENPluginAUXController : UIViewController
@property (nonatomic, readonly, strong) ZENPluginInfo * _Nonnull info;
@property (nonatomic, copy) void (^ _Nullable okHandler)(ZENPluginInfo * _Nonnull);
@property (nonatomic, copy) void (^ _Nullable cancelHandler)(void);
@property (nonatomic, copy) NSDictionary<NSString *, id> * _Nullable agreementParams;
@property (nonatomic, copy) NSDictionary<NSString *, id> * _Nullable downloadParams;
@property (nonatomic, copy) NSDictionary<NSString *, id> * _Nullable updateParams;
@property (nonatomic, copy) NSDictionary<NSString *, id> * _Nullable assetsParams;
@property (nonatomic, copy) NSString * _Nullable cannotLoadPlugin;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil SWIFT_UNAVAILABLE;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
- (nonnull instancetype)initWithInfo:(ZENPluginInfo * _Nonnull)info OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)viewDidLoad;
- (void)viewDidLayoutSubviews;
@end


SWIFT_CLASS_NAMED("ZENPluginConstants")
@interface ZENPluginConstants : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull pluginId;)
+ (NSString * _Nonnull)pluginId SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull assetsURL;)
+ (NSString * _Nonnull)assetsURL SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull menuImage;)
+ (NSString * _Nonnull)menuImage SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull backImage;)
+ (NSString * _Nonnull)backImage SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC12ZENPluginSDK18ZENPluginSDKObject")
@interface ZENPluginSDKObject : NSObject
- (nonnull instancetype)init:(NSDictionary<NSString *, id> * _Nonnull)dictionary;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (NSDictionary<NSString *, id> * _Nonnull)jsonObject SWIFT_WARN_UNUSED_RESULT;
- (NSData * _Nullable)jsonData SWIFT_WARN_UNUSED_RESULT;
+ (NSArray * _Nonnull)arrayOf:(NSArray * _Nonnull)array SWIFT_WARN_UNUSED_RESULT;
@end

enum ZENPluginType : NSInteger;
@class ZENSDKDependencies;
@class ZENSDKAssets;
@class ZENSDKSettings;
@class ZENSDKIcons;
enum ZENPluginStatus : NSInteger;

SWIFT_CLASS("_TtC12ZENPluginSDK13ZENPluginInfo")
@interface ZENPluginInfo : ZENPluginSDKObject
@property (nonatomic, readonly, copy) NSString * _Nonnull id;
@property (nonatomic, readonly) enum ZENPluginType type;
@property (nonatomic, readonly) NSInteger priority;
@property (nonatomic, readonly, copy) NSString * _Nullable name;
@property (nonatomic, readonly, copy) NSString * _Nullable version;
@property (nonatomic, readonly, copy) NSString * _Nullable language;
@property (nonatomic, readonly) BOOL enabled;
@property (nonatomic, readonly) BOOL forceUpdate;
@property (nonatomic, readonly, copy) NSString * _Nonnull autoUpdate;
@property (nonatomic, readonly) NSInteger licenseRevision;
@property (nonatomic, readonly) BOOL dataConsent;
@property (nonatomic, readonly, copy) NSString * _Nonnull menuPath;
@property (nonatomic, readonly, strong) ZENSDKDependencies * _Nullable dependencies;
@property (nonatomic, readonly, strong) ZENSDKAssets * _Nullable assets;
@property (nonatomic, readonly, strong) ZENSDKSettings * _Nullable settings;
@property (nonatomic, readonly, strong) ZENSDKAssets * _Nullable reactNative;
@property (nonatomic, readonly, strong) ZENSDKAssets * _Nullable native;
@property (nonatomic, readonly, strong) ZENSDKIcons * _Nullable icons;
@property (nonatomic, readonly) BOOL widget;
@property (nonatomic, readonly, copy) NSString * _Nullable brief;
@property (nonatomic, readonly, strong) ZENPluginInfo * _Nullable freshVersion;
- (nonnull instancetype)init:(NSDictionary<NSString *, id> * _Nonnull)dictionary;
- (NSDictionary<NSString *, id> * _Nonnull)jsonObject SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nullable)moduleName SWIFT_WARN_UNUSED_RESULT;
- (BOOL)devMode SWIFT_WARN_UNUSED_RESULT;
- (BOOL)downloaded SWIFT_WARN_UNUSED_RESULT;
- (BOOL)agreementAccepted SWIFT_WARN_UNUSED_RESULT;
- (BOOL)isWidgetAvailable SWIFT_WARN_UNUSED_RESULT;
- (BOOL)newVersionAvailable SWIFT_WARN_UNUSED_RESULT;
- (BOOL)isEnabled SWIFT_WARN_UNUSED_RESULT;
- (BOOL)assetsAvailable SWIFT_WARN_UNUSED_RESULT;
- (BOOL)assetsDownloaded SWIFT_WARN_UNUSED_RESULT;
- (void)loadImage:(NSString * _Nonnull)value completion:(void (^ _Nonnull)(UIImage * _Nonnull))completion;
- (void)saveValue:(NSString * _Nonnull)key value:(id _Nonnull)value;
- (id _Nullable)loadValue:(NSString * _Nonnull)key SWIFT_WARN_UNUSED_RESULT;
- (void)saveData:(NSDictionary<NSString *, id> * _Nonnull)data;
- (NSDictionary<NSString *, id> * _Nonnull)loadData SWIFT_WARN_UNUSED_RESULT;
- (UIImage * _Nullable)localImage:(NSString * _Nonnull)value SWIFT_WARN_UNUSED_RESULT;
- (enum ZENPluginStatus)canShowUI SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end



SWIFT_PROTOCOL_NAMED("ZENPluginProtocol")
@protocol ZENPluginProtocol
- (UIViewController * _Nullable)pluginController SWIFT_WARN_UNUSED_RESULT;
- (void)initializePlugin:(NSDictionary<NSString *, id> * _Nonnull)params;
- (void)stopBackgroundProcesses;
- (void)resumeBackgroundProcesses;
- (void)addObserver;
- (void)removeObserver;
@optional
- (void)didReceivePushNotification:(NSDictionary<NSString *, id> * _Nonnull)aps;
@end

@class ZENPluginSDKStyle;
@class ZENWidget;
@class ZENWidgetLine;
@class UIFont;

SWIFT_CLASS("_TtC12ZENPluginSDK12ZENPluginSDK")
@interface ZENPluginSDK : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, strong) ZENPluginSDK * _Nonnull instance;)
+ (ZENPluginSDK * _Nonnull)instance SWIFT_WARN_UNUSED_RESULT;
+ (void)setInstance:(ZENPluginSDK * _Nonnull)value;
@property (nonatomic, readonly, strong) ZENPluginSDKStyle * _Nonnull style;
@property (nonatomic, weak) id <HostAppProtocol> _Nullable hostAppDelegate;
/// //// handlers ////////
@property (nonatomic, copy) void (^ _Nullable pluginsListUpdated)(NSArray<ZENPluginInfo *> * _Nonnull);
@property (nonatomic, copy) void (^ _Nullable pluginsLoadingFailed)(void);
@property (nonatomic, copy) void (^ _Nullable pluginDownloaded)(ZENPluginInfo * _Nonnull);
@property (nonatomic, copy) void (^ _Nullable pluginDownloadingFailed)(ZENPluginInfo * _Nonnull);
@property (nonatomic, copy) void (^ _Nullable assetsDownloaded)(ZENPluginInfo * _Nonnull);
@property (nonatomic, copy) void (^ _Nullable assetsDownloadingFailed)(ZENPluginInfo * _Nonnull);
@property (nonatomic, copy) void (^ _Nullable widgetInfoUpdated)(ZENWidget * _Nonnull);
@property (nonatomic, copy) void (^ _Nullable widgetLineUpdated)(ZENWidgetLine * _Nonnull);
@property (nonatomic, copy) void (^ _Nullable pluginWantsToShowUI)(ZENPluginInfo * _Nonnull);
@property (nonatomic, copy) void (^ _Nullable pluginWantsToShowMenu)(void);
@property (nonatomic, copy) void (^ _Nullable pluginWantsToDismiss)(void);
@property (nonatomic, copy) void (^ _Nullable pluginLoadingComplete)(ZENPluginInfo * _Nonnull);
/// //////////////////////
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (void)initializeSDK:(NSDictionary<NSString *, id> * _Nonnull)params;
- (void)updatePluginsFromNetwork;
- (NSArray<ZENPluginInfo *> * _Nonnull)pluginsOrderedBy:(enum ZENOrder)order section:(NSString * _Nullable)section SWIFT_WARN_UNUSED_RESULT;
- (NSArray<ZENPluginInfo *> * _Nonnull)widgetsOrderedBy:(enum ZENOrder)order section:(NSString * _Nullable)section SWIFT_WARN_UNUSED_RESULT;
- (ZENPluginAUXController * _Nullable)loadAUXController:(ZENPluginInfo * _Nonnull)info messages:(NSDictionary<NSString *, id> * _Nullable)messages SWIFT_WARN_UNUSED_RESULT;
- (UIViewController * _Nullable)loadUI:(ZENPluginInfo * _Nonnull)info SWIFT_WARN_UNUSED_RESULT;
- (ZENWidget * _Nullable)loadWidget:(ZENPluginInfo * _Nonnull)info SWIFT_WARN_UNUSED_RESULT;
- (ZENPluginInfo * _Nullable)pluginByIdentity:(NSString * _Nonnull)identity SWIFT_WARN_UNUSED_RESULT;
- (void)addObserver:(ZENPluginInfo * _Nonnull)info;
- (void)removeObserver:(ZENPluginInfo * _Nonnull)info;
- (void)revokeDataProcessing:(ZENPluginInfo * _Nonnull)info completion:(void (^ _Nonnull)(NSDictionary<NSString *, id> * _Nullable, NSError * _Nullable))completion;
- (BOOL)isPluginLoaded:(ZENPluginInfo * _Nonnull)info SWIFT_WARN_UNUSED_RESULT;
- (void)closePlugin:(ZENPluginInfo * _Nonnull)info;
- (void)closeAllPlugins;
- (void)removeAssets:(ZENPluginInfo * _Nonnull)info;
- (void)removePlugin:(ZENPluginInfo * _Nonnull)info;
- (void)switchSandBoxMode:(ZENPluginInfo * _Nonnull)info devURL:(NSString * _Nullable)devURL;
- (void)setCustomStyle:(NSDictionary<NSString *, id> * _Nonnull)params;
- (void)setDefaultFont:(UIFont * _Nonnull)font;
- (void)setBaseURL:(NSString * _Nonnull)url;
- (void)setHeader:(NSString * _Nonnull)key value:(NSString * _Nonnull)value;
- (void)didReceivePushWithNotification:(NSDictionary<NSString *, id> * _Nonnull)notification;
/// call it from didFinishLaunchingWithOptions (for example) or implement your own code
- (void)registerForLocalNotifications:(UIApplication * _Nonnull)application;
/// call it from applicationDidBecomeActive or implement your own code
- (void)removeLocalNotifications:(UIApplication * _Nonnull)application;
@end


@interface ZENPluginSDK (SWIFT_EXTENSION(ZENPluginSDK))
- (void)getUserData:(void (^ _Nonnull)(NSError * _Nullable, id _Nullable))completion;
@end


@interface ZENPluginSDK (SWIFT_EXTENSION(ZENPluginSDK)) <CLLocationManagerDelegate>
- (void)isLocationServiceAvailable:(void (^ _Nonnull)(BOOL))callback;
@end



@interface ZENPluginSDK (SWIFT_EXTENSION(ZENPluginSDK))
- (void)createNotification:(NSInteger)identity text:(NSString * _Nonnull)text datetime:(NSDate * _Nonnull)datetime sound:(NSString * _Nonnull)sound;
- (void)updateNotification:(NSInteger)identity text:(NSString * _Nonnull)text datetime:(NSDate * _Nonnull)datetime sound:(NSString * _Nonnull)sound;
- (void)deleteNotification:(NSInteger)identity;
@end



@interface ZENPluginSDK (SWIFT_EXTENSION(ZENPluginSDK))
- (void)APIGETRequest:(id <ZENPluginProtocol> _Nonnull)sender url:(NSURL * _Nonnull)url completion:(void (^ _Nonnull)(NSError * _Nullable, id _Nullable))completion;
- (void)APIPOSTRequest:(id <ZENPluginProtocol> _Nonnull)sender url:(NSURL * _Nonnull)url params:(NSDictionary<NSString *, id> * _Nullable)params completion:(void (^ _Nonnull)(NSError * _Nullable, id _Nullable))completion;
- (void)APIRequest:(id <ZENPluginProtocol> _Nonnull)sender url:(NSURL * _Nonnull)url method:(NSString * _Nonnull)method params:(NSDictionary<NSString *, id> * _Nullable)params completion:(void (^ _Nonnull)(NSError * _Nullable, id _Nullable))completion;
- (void)APIRequest:(id <ZENPluginProtocol> _Nonnull)sender url:(NSURL * _Nonnull)url method:(NSString * _Nonnull)method params:(NSDictionary<NSString *, id> * _Nullable)params headers:(NSDictionary<NSString *, NSString *> * _Nullable)headers completion:(void (^ _Nonnull)(NSError * _Nullable, id _Nullable))completion;
@end


@interface ZENPluginSDK (SWIFT_EXTENSION(ZENPluginSDK))
- (void)trackScreenView:(NSString * _Nonnull)name;
- (void)trackScreenView:(NSString * _Nonnull)name trackingId:(NSString * _Nonnull)trackingId;
- (void)trackEvent:(NSString * _Nonnull)category action:(NSString * _Nonnull)action;
- (void)trackEvent:(NSString * _Nonnull)category action:(NSString * _Nonnull)action optionalValues:(NSDictionary<NSString *, id> * _Nullable)optionalValues;
- (void)trackEvent:(NSString * _Nonnull)category action:(NSString * _Nonnull)action optionalValues:(NSDictionary<NSString *, id> * _Nullable)optionalValues trackingId:(NSString * _Nonnull)trackingId;
@end



@class UIBarButtonItem;

@interface ZENPluginSDK (SWIFT_EXTENSION(ZENPluginSDK))
- (NSString * _Nullable)pluginId:(id <ZENPluginProtocol> _Nonnull)sender SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nullable)assetsURL:(id <ZENPluginProtocol> _Nonnull)sender SWIFT_WARN_UNUSED_RESULT;
- (ZENPluginInfo * _Nullable)pluginMetadata:(id <ZENPluginProtocol> _Nonnull)sender SWIFT_WARN_UNUSED_RESULT;
- (void)sendWidgetData:(id <ZENPluginProtocol> _Nonnull)sender widget:(ZENWidget * _Nonnull)widget;
- (void)requestToOpenController:(id <ZENPluginProtocol> _Nonnull)sender;
- (void)requestToShowMenu;
- (void)requestToClose;
- (NSString * _Nullable)menuButtonImage SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nullable)backButtonImage SWIFT_WARN_UNUSED_RESULT;
- (UIBarButtonItem * _Nullable)menuButton SWIFT_WARN_UNUSED_RESULT;
- (void)saveValue:(id <ZENPluginProtocol> _Nonnull)sender key:(NSString * _Nonnull)key value:(id _Nonnull)value;
- (id _Nullable)loadValue:(id <ZENPluginProtocol> _Nonnull)sender key:(NSString * _Nonnull)key SWIFT_WARN_UNUSED_RESULT;
- (void)saveData:(id <ZENPluginProtocol> _Nonnull)sender dic:(NSDictionary<NSString *, id> * _Nonnull)dic;
- (NSDictionary<NSString *, id> * _Nonnull)loadData:(id <ZENPluginProtocol> _Nonnull)sender SWIFT_WARN_UNUSED_RESULT;
- (void)sendEvent:(id <ZENPluginProtocol> _Nonnull)sender type:(NSString * _Nonnull)type payload:(NSDictionary<NSString *, id> * _Nonnull)payload;
- (void)revokeDataProcessingConsent:(id <ZENPluginProtocol> _Nonnull)sender completion:(void (^ _Nonnull)(NSDictionary<NSString *, id> * _Nullable, NSError * _Nullable))completion;
@end

@class UINavigationController;

@interface ZENPluginSDK (SWIFT_EXTENSION(ZENPluginSDK))
+ (void)runPlugin:(UIViewController * _Nonnull)sender info:(ZENPluginInfo * _Nonnull)info push:(BOOL)push ncClass:(SWIFT_METATYPE(UINavigationController) _Nonnull)ncClass;
@end


SWIFT_CLASS("_TtC12ZENPluginSDK16ZENPluginSDKInfo")
@interface ZENPluginSDKInfo : ZENPluginSDKObject
- (nonnull instancetype)init:(NSDictionary<NSString *, id> * _Nonnull)dictionary;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC12ZENPluginSDK18ZENPluginSDKMethod")
@interface ZENPluginSDKMethod : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


@class ZENPluginSDKStyleFont;
@class ZENPluginSDKStyleView;
@class ZENPluginSDKStyleTable;
@class ZENPluginSDKStyleButtons;

SWIFT_CLASS("_TtC12ZENPluginSDK17ZENPluginSDKStyle")
@interface ZENPluginSDKStyle : NSObject
@property (nonatomic, readonly, strong) ZENPluginSDKStyleFont * _Nonnull fonts;
@property (nonatomic, readonly, strong) ZENPluginSDKStyleView * _Nonnull view;
@property (nonatomic, readonly, strong) ZENPluginSDKStyleTable * _Nonnull table;
@property (nonatomic, readonly, strong) ZENPluginSDKStyleButtons * _Nonnull buttons;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtCC12ZENPluginSDK17ZENPluginSDKStyle23ZENPluginSDKStyleObject")
@interface ZENPluginSDKStyleObject : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtCC12ZENPluginSDK17ZENPluginSDKStyle21ZENPluginSDKStyleFont")
@interface ZENPluginSDKStyleFont : ZENPluginSDKStyleObject
@property (nonatomic, readonly, strong) UIFont * _Nonnull title;
@property (nonatomic, readonly, strong) UIFont * _Nonnull subtitle;
@property (nonatomic, readonly, strong) UIFont * _Nonnull body;
@property (nonatomic, readonly, strong) UIFont * _Nonnull defaultFont;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtCC12ZENPluginSDK17ZENPluginSDKStyle21ZENPluginSDKStyleView")
@interface ZENPluginSDKStyleView : ZENPluginSDKStyleObject
@property (nonatomic, readonly, strong) UIColor * _Nonnull backgroundColor;
@property (nonatomic, readonly, strong) UIColor * _Nonnull textColor;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtCC12ZENPluginSDK17ZENPluginSDKStyle22ZENPluginSDKStyleTable")
@interface ZENPluginSDKStyleTable : ZENPluginSDKStyleObject
@property (nonatomic, readonly, strong) UIColor * _Nonnull backgroundColor;
@property (nonatomic, readonly, strong) UIColor * _Nonnull cellBackgroundColor;
@property (nonatomic, readonly, strong) UIColor * _Nonnull separatorColor;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtCC12ZENPluginSDK17ZENPluginSDKStyle24ZENPluginSDKStyleButtons")
@interface ZENPluginSDKStyleButtons : ZENPluginSDKStyleObject
@property (nonatomic, readonly, strong) UIColor * _Nonnull backgroundColor;
@property (nonatomic, readonly, strong) UIColor * _Nonnull titleColor;
@property (nonatomic, readonly, strong) UIColor * _Nonnull tintColor;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


typedef SWIFT_ENUM_NAMED(NSInteger, ZENPluginStatus, "ZENPluginStatus", open) {
  ZENPluginStatusCanShowUI = 0,
  ZENPluginStatusNoLicense = 1,
  ZENPluginStatusNeedUpdate = 2,
  ZENPluginStatusNoBundle = 3,
  ZENPluginStatusNoAssets = 4,
};

typedef SWIFT_ENUM(NSInteger, ZENPluginType, open) {
  ZENPluginTypeNative = 0,
  ZENPluginTypeReact = 1,
};


SWIFT_CLASS("_TtC12ZENPluginSDK12ZENSDKAssets")
@interface ZENSDKAssets : ZENPluginSDKObject
@property (nonatomic, readonly, copy) NSString * _Nullable bundleUrl;
@property (nonatomic, readonly, copy) NSString * _Nullable checksum;
@property (nonatomic, readonly, copy) NSString * _Nullable binary;
@property (nonatomic, readonly, copy) NSString * _Nullable moduleName;
- (nonnull instancetype)init:(NSDictionary<NSString *, id> * _Nonnull)dictionary;
- (NSDictionary<NSString *, id> * _Nonnull)jsonObject SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC12ZENPluginSDK18ZENSDKConfirmation")
@interface ZENSDKConfirmation : ZENPluginSDKObject
- (nonnull instancetype)init:(NSDictionary<NSString *, id> * _Nonnull)dictionary;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

enum ZENSDKEnvironment : NSInteger;

SWIFT_CLASS("_TtC12ZENPluginSDK15ZENSDKConstants")
@interface ZENSDKConstants : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSTimeInterval tryDownloadAgainTimeout;)
+ (NSTimeInterval)tryDownloadAgainTimeout SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSTimeInterval sendEventInterval;)
+ (NSTimeInterval)sendEventInterval SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger sendEventAmount;)
+ (NSInteger)sendEventAmount SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger maxEventCount;)
+ (NSInteger)maxEventCount SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull platform;)
+ (NSString * _Nonnull)platform SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull app_id;)
+ (NSString * _Nonnull)app_id SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull errorDomain;)
+ (NSString * _Nonnull)errorDomain SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull client_key;)
+ (NSString * _Nonnull)client_key SWIFT_WARN_UNUSED_RESULT;
+ (enum ZENSDKEnvironment)environment:(NSString * _Nullable)env SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC12ZENPluginSDK18ZENSDKDependencies")
@interface ZENSDKDependencies : ZENPluginSDKObject
@property (nonatomic, readonly, copy) NSString * _Nullable sdkVersion;
@property (nonatomic, readonly, copy) NSString * _Nullable appVersion;
- (nonnull instancetype)init:(NSDictionary<NSString *, id> * _Nonnull)dictionary;
- (NSDictionary<NSString *, id> * _Nonnull)jsonObject SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

typedef SWIFT_ENUM(NSInteger, ZENSDKEnvironment, open) {
  ZENSDKEnvironmentDevelopment = 0,
  ZENSDKEnvironmentTesting = 1,
  ZENSDKEnvironmentProduction = 2,
};


SWIFT_CLASS("_TtC12ZENPluginSDK11ZENSDKIcons")
@interface ZENSDKIcons : ZENPluginSDKObject
@property (nonatomic, readonly, copy) NSString * _Nullable twoX;
@property (nonatomic, readonly, copy) NSString * _Nullable threeX;
- (nonnull instancetype)init:(NSDictionary<NSString *, id> * _Nonnull)dictionary;
- (NSDictionary<NSString *, id> * _Nonnull)jsonObject SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC12ZENPluginSDK14ZENSDKSettings")
@interface ZENSDKSettings : ZENPluginSDKObject
@property (nonatomic, readonly, copy) NSString * _Nullable layoutVariant;
@property (nonatomic, readonly, copy) NSString * _Nullable backendApi;
- (nonnull instancetype)init:(NSDictionary<NSString *, id> * _Nonnull)dictionary;
- (NSDictionary<NSString *, id> * _Nonnull)jsonObject SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC12ZENPluginSDK15ZENSDKapiParams")
@interface ZENSDKapiParams : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull appVersion;)
+ (NSString * _Nonnull)appVersion SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull sdkVersion;)
+ (NSString * _Nonnull)sdkVersion SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull country;)
+ (NSString * _Nonnull)country SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull language;)
+ (NSString * _Nonnull)language SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull device_id;)
+ (NSString * _Nonnull)device_id SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull platform;)
+ (NSString * _Nonnull)platform SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull sim_country;)
+ (NSString * _Nonnull)sim_country SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull dealer_country;)
+ (NSString * _Nonnull)dealer_country SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull plugin;)
+ (NSString * _Nonnull)plugin SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull plugins;)
+ (NSString * _Nonnull)plugins SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC12ZENPluginSDK15ZENSDKenvParams")
@interface ZENSDKenvParams : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull development;)
+ (NSString * _Nonnull)development SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull testing;)
+ (NSString * _Nonnull)testing SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull production;)
+ (NSString * _Nonnull)production SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC12ZENPluginSDK16ZENSDKinfoParams")
@interface ZENSDKinfoParams : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull device_id;)
+ (NSString * _Nonnull)device_id SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull app_version;)
+ (NSString * _Nonnull)app_version SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull sdk_version;)
+ (NSString * _Nonnull)sdk_version SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull environment;)
+ (NSString * _Nonnull)environment SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull language;)
+ (NSString * _Nonnull)language SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull sim_country;)
+ (NSString * _Nonnull)sim_country SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull dealer_country;)
+ (NSString * _Nonnull)dealer_country SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull dealer;)
+ (NSString * _Nonnull)dealer SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull clientKey;)
+ (NSString * _Nonnull)clientKey SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC12ZENPluginSDK19ZENSDKnotifications")
@interface ZENSDKnotifications : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSNotificationName _Nonnull pluginsListUpdated;)
+ (NSNotificationName _Nonnull)pluginsListUpdated SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSNotificationName _Nonnull pluginsLoadingFailed;)
+ (NSNotificationName _Nonnull)pluginsLoadingFailed SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSNotificationName _Nonnull pluginDownloaded;)
+ (NSNotificationName _Nonnull)pluginDownloaded SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSNotificationName _Nonnull pluginDownloadingFailed;)
+ (NSNotificationName _Nonnull)pluginDownloadingFailed SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSNotificationName _Nonnull assetsDownloaded;)
+ (NSNotificationName _Nonnull)assetsDownloaded SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSNotificationName _Nonnull assetsDownloadingFailed;)
+ (NSNotificationName _Nonnull)assetsDownloadingFailed SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSNotificationName _Nonnull widgetInfoUpdated;)
+ (NSNotificationName _Nonnull)widgetInfoUpdated SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSNotificationName _Nonnull widgetLineUpdated;)
+ (NSNotificationName _Nonnull)widgetLineUpdated SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSNotificationName _Nonnull pluginWantsToShowUI;)
+ (NSNotificationName _Nonnull)pluginWantsToShowUI SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSNotificationName _Nonnull pluginWantsToShowMenu;)
+ (NSNotificationName _Nonnull)pluginWantsToShowMenu SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSNotificationName _Nonnull pluginWantsToDismiss;)
+ (NSNotificationName _Nonnull)pluginWantsToDismiss SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSNotificationName _Nonnull pluginLoadingComplete;)
+ (NSNotificationName _Nonnull)pluginLoadingComplete SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class ZENPluginSDKStyleParamsFont;
@class ZENPluginSDKStyleParamsView;
@class ZENPluginSDKStyleParamsTable;
@class ZENPluginSDKStyleParamsButtons;

SWIFT_CLASS("_TtC12ZENPluginSDK17ZENSDKstyleParams")
@interface ZENSDKstyleParams : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) SWIFT_METATYPE(ZENPluginSDKStyleParamsFont) _Nonnull fonts;)
+ (SWIFT_METATYPE(ZENPluginSDKStyleParamsFont) _Nonnull)fonts SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) SWIFT_METATYPE(ZENPluginSDKStyleParamsView) _Nonnull view;)
+ (SWIFT_METATYPE(ZENPluginSDKStyleParamsView) _Nonnull)view SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) SWIFT_METATYPE(ZENPluginSDKStyleParamsTable) _Nonnull table;)
+ (SWIFT_METATYPE(ZENPluginSDKStyleParamsTable) _Nonnull)table SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) SWIFT_METATYPE(ZENPluginSDKStyleParamsButtons) _Nonnull buttons;)
+ (SWIFT_METATYPE(ZENPluginSDKStyleParamsButtons) _Nonnull)buttons SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtCC12ZENPluginSDK17ZENSDKstyleParams27ZENPluginSDKStyleParamsFont")
@interface ZENPluginSDKStyleParamsFont : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull title;)
+ (NSString * _Nonnull)title SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull subtitle;)
+ (NSString * _Nonnull)subtitle SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull body;)
+ (NSString * _Nonnull)body SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSArray<NSString *> * _Nonnull allKeys;)
+ (NSArray<NSString *> * _Nonnull)allKeys SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtCC12ZENPluginSDK17ZENSDKstyleParams27ZENPluginSDKStyleParamsView")
@interface ZENPluginSDKStyleParamsView : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull backgroundColor;)
+ (NSString * _Nonnull)backgroundColor SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull textColor;)
+ (NSString * _Nonnull)textColor SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSArray<NSString *> * _Nonnull allKeys;)
+ (NSArray<NSString *> * _Nonnull)allKeys SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtCC12ZENPluginSDK17ZENSDKstyleParams28ZENPluginSDKStyleParamsTable")
@interface ZENPluginSDKStyleParamsTable : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull backgroundColor;)
+ (NSString * _Nonnull)backgroundColor SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull cellBackgroundColor;)
+ (NSString * _Nonnull)cellBackgroundColor SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull separatorColor;)
+ (NSString * _Nonnull)separatorColor SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSArray<NSString *> * _Nonnull allKeys;)
+ (NSArray<NSString *> * _Nonnull)allKeys SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtCC12ZENPluginSDK17ZENSDKstyleParams30ZENPluginSDKStyleParamsButtons")
@interface ZENPluginSDKStyleParamsButtons : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull backgroundColor;)
+ (NSString * _Nonnull)backgroundColor SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull titleColor;)
+ (NSString * _Nonnull)titleColor SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull tintColor;)
+ (NSString * _Nonnull)tintColor SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSArray<NSString *> * _Nonnull allKeys;)
+ (NSArray<NSString *> * _Nonnull)allKeys SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC12ZENPluginSDK9ZENWidget")
@interface ZENWidget : ZENPluginSDKObject
@property (nonatomic, copy) NSString * _Nullable pluginId;
@property (nonatomic, strong) UIImage * _Nullable image;
@property (nonatomic, copy) NSURL * _Nullable imageURL;
@property (nonatomic, copy) NSString * _Nullable title;
@property (nonatomic, copy) NSArray<ZENWidgetLine *> * _Nullable lines;
- (nonnull instancetype)init:(NSDictionary<NSString *, id> * _Nonnull)dictionary;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC12ZENPluginSDK15ZENWidgetAction")
@interface ZENWidgetAction : NSObject
@property (nonatomic, weak) ZENWidgetLine * _Nullable line;
@property (nonatomic, copy) void (^ _Nullable handler)(void);
@property (nonatomic, copy) NSString * _Nullable title;
@property (nonatomic, strong) UIImage * _Nullable image;
@property (nonatomic, copy) NSString * _Nullable imageURL;
@property (nonatomic) BOOL isEnabled;
@property (nonatomic) BOOL isHidden;
- (nonnull instancetype)initWithTitle:(NSString * _Nullable)title image:(UIImage * _Nullable)image handler:(void (^ _Nullable)(void))handler;
- (nonnull instancetype)initWithTitle:(NSString * _Nullable)title imageURL:(NSString * _Nullable)imageURL handler:(void (^ _Nullable)(void))handler;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

enum ZENlineType : NSInteger;

SWIFT_CLASS("_TtC12ZENPluginSDK13ZENWidgetLine")
@interface ZENWidgetLine : ZENPluginSDKObject
@property (nonatomic, weak) ZENWidget * _Nullable widget;
@property (nonatomic) enum ZENlineType type;
@property (nonatomic) NSInteger lines;
@property (nonatomic, copy) NSString * _Nullable richText;
@property (nonatomic, copy) NSURL * _Nullable iconName;
@property (nonatomic, strong) UIImage * _Nullable icon;
@property (nonatomic) float progress;
@property (nonatomic) BOOL loading;
@property (nonatomic, copy) NSArray<ZENWidgetAction *> * _Nullable actions;
- (nonnull instancetype)init:(NSDictionary<NSString *, id> * _Nonnull)dictionary;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

typedef SWIFT_ENUM(NSInteger, ZENlineType, open) {
  ZENlineTypeNone = 0,
  ZENlineTypeText = 1,
  ZENlineTypeIconText = 2,
  ZENlineTypeIconProgress = 3,
  ZENlineTypeLoading = 4,
  ZENlineTypeButtons = 5,
};


SWIFT_CLASS("_TtC12ZENPluginSDK10confParams")
@interface confParams : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull titleText;)
+ (NSString * _Nonnull)titleText SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull bodyText;)
+ (NSString * _Nonnull)bodyText SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull okButtonText;)
+ (NSString * _Nonnull)okButtonText SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull cancelButtonText;)
+ (NSString * _Nonnull)cancelButtonText SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC12ZENPluginSDK14lineTypeParams")
@interface lineTypeParams : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC12ZENPluginSDK14messagesParams")
@interface messagesParams : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull agreementParams;)
+ (NSString * _Nonnull)agreementParams SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull downloadParams;)
+ (NSString * _Nonnull)downloadParams SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull updateParams;)
+ (NSString * _Nonnull)updateParams SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull assetsParams;)
+ (NSString * _Nonnull)assetsParams SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull cannotLoadPlugin;)
+ (NSString * _Nonnull)cannotLoadPlugin SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC12ZENPluginSDK12widgetParams")
@interface widgetParams : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop
#endif

#endif
